import argparse
from datetime import datetime
import os
from pathlib import Path
import logging
import signal
import sys
import traceback

import ase.io

from predict_snar import config, results
from predict_snar.descriptors import calculate_descriptors
from predict_snar.helpers import set_config, set_resources, cd, get_nucleophilic_centers, set_electronic_temp, write_reaction_database
from predict_snar.helpers import get_fragment_distance, set_info, get_electronic_temp
from predict_snar.jobs import optimize_intermediate, optimize_react_complex, optimize_prod_complex, optimize_xtb, optimize_dft, find_ts, find_ts_scan, find_ts_GIC_scan
from predict_snar.jobs import do_clustering_xtb
from predict_snar.parsers import ConfigParser, XTBParser, SystemParser
from predict_snar.smiles import SmilesToXYZ

# Create logger
logger = logging.getLogger("predict_snar")
logger.setLevel(logging.INFO)

# Create file handler
fh = logging.FileHandler('predict_snar.log')

# create formatter
formatter = logging.Formatter(fmt='%(asctime)s (%(module)s)     %(message)s',
                              datefmt='%Y-%m-%d %H:%M:%S')

# add formatter to ch
fh.setFormatter(formatter)

# add ch to logger
logger.addHandler(fh)

def handler(signum=None, frame=None):
    """Function to handle abnormal program termination"""
    logger.critical("PROGRAM EXITED ABNORMALLY.")
    traceback.print_exc()
    sys.exit()

def main():
    # Set start time
    start_time = datetime.now()

    # Define handler if the program crashes
    signal.signal(signal.SIGTERM, handler)

    # Capture arguments
    parser = argparse.ArgumentParser()
    parser.add_argument("input", help="Smiles of reaction", type=str)
    parser.add_argument("-m", "--mem", help="Amount of memory in GB", type=int)
    parser.add_argument("-p", "--n_procs", help="Number of processors", type=int)
    args = parser.parse_args()
    n_procs = args.n_procs
    mem = args.mem
    smiles = args.input

    # Load the program options from the config file
    options = ConfigParser("config")
    set_config(options)
    
    # Make database directory if it does not exist
    db_path = config.directories["database"]
    if db_path:
        db_path = Path(db_path)
        if not db_path.is_dir():
            try:
                db_path.mkdir()
            except FileExistsError:
                pass
    #!TODO this would need to take into account the temperatur in the solvent as
    # well. Disabled for now    
    #    if check_reaction_database(smiles, db_path.as_posix()):
    #        logger.info("Reaction already in database. Exiting.")
    #        sys.exit()

    # Parse SMILES
    logger.info("Processing reaction smiles...")
    smiles_to_xyz = SmilesToXYZ(smiles)
    smiles_to_xyz.write_info()
    smiles_to_xyz.write_xyz()
    logger.info("...processing completed.")

    # Read the config file generated by Smiles parser
    options = SystemParser("system_info")
    set_info(options)

    # TODO Check molecular database to get results that have already been
    # calculated.

    # Set the number of processors and amount of memory
    set_resources(n_procs, mem)

    # Check for intramolecular reaction
    config.intramolecular = smiles_to_xyz.intramolecular

    # Read in reactive atoms info
    central_atom = config.reactive_atoms["central_atom"]
    lg_atom = config.reactive_atoms["lg_atom"]
    fragment_lg = config.reactive_atoms["fragment_lg"]
    fragment_substrate = config.reactive_atoms["fragment_substrate"]
    nu_atom = config.reactive_atoms["nu_atom"]
    fragment_nu = config.reactive_atoms["fragment_nu"]
    nu_h_atoms = config.reactive_atoms["nu_h_atoms"]
    fragment_nu = [atom for atom in fragment_nu if atom not in nu_h_atoms]

    # Set variables
    config.flat_PES = False
    config.concerted = True

    # Store SMILES, Inchi, Inchikey and rdkit mol results
    results.smiles = {"substrate": smiles_to_xyz.smiles["substrate"],
                      "leaving_group": smiles_to_xyz.smiles["lg"],
                      "product": smiles_to_xyz.smiles["product"],
                      "reaction": smiles_to_xyz.smiles["reaction"],
                      "reaction_orig": smiles_to_xyz.smiles["reaction_orig"],
                      }
    results.inchi = {"substrate": smiles_to_xyz.inchi["substrate"],
                     "leaving_group": smiles_to_xyz.inchi["lg"],
                     "product": smiles_to_xyz.inchi["product"],
                     }                   
    results.inchi_key = {"substrate": smiles_to_xyz.inchi_key["substrate"],
                         "leaving_group": smiles_to_xyz.inchi_key["lg"],
                         "product": smiles_to_xyz.inchi_key["product"],
                         }    
    results.rdkit_mols = {
        "substrate": smiles_to_xyz.substrate,
        "product": smiles_to_xyz.lg,
        "leaving_group": smiles_to_xyz.lg,
        "reaction_complex": smiles_to_xyz.reaction_complex,
        }
    if not config.intramolecular:
        results.smiles["nucleophile"] = smiles_to_xyz.smiles["nu"]
        results.inchi["nucleophile"] = smiles_to_xyz.inchi["nu"]
        results.inchi_key["nucleophile"] = smiles_to_xyz.inchi_key["nu"]
        results.rdkit_mols["nucleophile"] = smiles_to_xyz.nu
    if config.agent:
        results.smiles["agent"] = smiles_to_xyz.smiles["agent"]
        results.inchi["agent"] = smiles_to_xyz.inchi["agent"]
        results.inchi_key["agent"] = smiles_to_xyz.inchi_key["agent"]
        results.rdkit_mols["agent"] = smiles_to_xyz.agent

    # Make dir for optimized files
    os.mkdir("optimized_structures")

    # Read the structures from MM-optimized xyz files
    jobs = [
        "substrate",
        "product",
        "leaving_group",
        ]
    if not config.intramolecular:
        jobs.append("nucleophile")
    if config.agent:
        jobs.append("agent")
    
    for name in jobs:
        atoms = ase.io.read(f"xyz_from_smiles/{name}.xyz")
        atoms.info["charge"] = config.charges[name]
        results.mm_atoms[name] = atoms
    
    # Optimize with xtb and select electronic temperature
    os.mkdir("xtb_structures")
    with cd("xtb_structures"):
        for name in jobs:
            atoms = results.mm_atoms[name]
            options = {}
            if name == "nucleophile" or (config.intramolecular and name == "substrate"):
                options = {"lmo": True}
            opt_atoms = optimize_xtb(atoms, name, options)
            results.xtb_atoms[name] = opt_atoms

    # Determine electronic temperature based on HL-gap
    data_substrate = XTBParser("xtb_structures/substrate/xtb.out")
    if not config.intramolecular:
        data_nucleophile = XTBParser("xtb_structures/nucleophile/xtb.out")
    else:
        data_nucleophile = XTBParser("xtb_structures/substrate/xtb.out")
    e_homo = data_nucleophile.homo
    e_lumo = data_substrate.lumo
    hl_gap = e_lumo - e_homo
    el_temp = get_electronic_temp(hl_gap, separated=True)
    set_electronic_temp(el_temp)
    
    # Set up bond lengths for optimization of intermediate.
    config.general_options["intermediate_center_nu"] = results.xtb_atoms["product"].get_distance(config.reactive_atoms["central_atom_prod"] - 1, config.reactive_atoms["added_atom"] - 1)
    config.general_options["intermediate_center_lg"] = results.xtb_atoms["substrate"].get_distance(config.reactive_atoms["central_atom"] - 1, config.reactive_atoms["lg_atom"] - 1)

    # Get the nucleophilic centers
    if not config.intramolecular:
        nucleophilic_centers = get_nucleophilic_centers("xtb_structures/nucleophile/xtb.out")
        nucleophilic_centers = [center + len(fragment_substrate) + len(fragment_lg) for center in nucleophilic_centers]
    else:
        nucleophilic_centers = get_nucleophilic_centers("xtb_structures/substrate/xtb.out")
    nucleophilic_centers.remove(nu_atom)
    config.nucleophilic_centers = nucleophilic_centers

    # Read in reaction complex
    if config.agent:
        results.mm_atoms["reaction_complex"] = ase.io.read("xyz_from_smiles/reaction_complex_agent.xyz")
    else:
        results.mm_atoms["reaction_complex"] = ase.io.read("xyz_from_smiles/reaction_complex.xyz")

    complex_charge = config.charges["substrate"]
    if not config.intramolecular:
        complex_charge += config.charges["nucleophile"]       
    if config.agent:
        complex_charge += config.charges["agent"]
    results.mm_atoms["reaction_complex"].info["charge"] = complex_charge
    
    # Set fragments distance
    central_symbol = results.mm_atoms["reaction_complex"].get_chemical_symbols()[central_atom - 1] 
    nu_symbol = results.mm_atoms["reaction_complex"].get_chemical_symbols()[nu_atom - 1] 
    config.general_options["fragment_distance_reactant"] = get_fragment_distance(central_symbol, nu_symbol)

    central_symbol = results.mm_atoms["reaction_complex"].get_chemical_symbols()[central_atom - 1] 
    lg_symbol = results.mm_atoms["reaction_complex"].get_chemical_symbols()[lg_atom - 1] 
    config.general_options["fragment_distance_product"] = get_fragment_distance(central_symbol, lg_symbol)

    # Optimize reaction complex
    with cd("xtb_structures"):
        optimize_react_complex()

    # Set Nu-H distances
    config.general_options["nu_h_distances"] = [results.xtb_atoms["reaction_complex"].get_distance(nu_atom - 1, h_atom - 1) for h_atom in config.reactive_atoms["nu_h_atoms"]]

    # Optimize the intermediate with DFT
    optimize_intermediate()
    if results.dft_atoms["intermediate"]:
        config.concerted = False
        ase.io.write("optimized_structures/intermediate.xyz", results.dft_atoms["intermediate"], plain=True)
    else:
        config.concerted = True
    
    # Optimize product complex
    with cd("xtb_structures"):
        optimize_prod_complex()

    # Optimize reactant if negatively charged
    os.mkdir("dft_structures")
    if config.charges["nu_atom"] < 0 and not config.intramolecular:
        jobs = ["nucleophile"]
        with cd("dft_structures"):
            for name in jobs:
                os.mkdir(name)
                with cd(name):
                    logger.info(f"Optimizing {name} with DFT...")
                    atoms = results.xtb_atoms[name]
                    opt_dft_atoms = optimize_dft(atoms)
                    logger.info("...optimization completed.")
                    ase.io.write(f"../../optimized_structures/{name}.xyz", opt_dft_atoms, plain=True)
                    results.dft_atoms[name] = opt_dft_atoms        

    # Optimize the TSs along the path
    if config.concerted:
        # Find TS for concerted path
        os.mkdir("concerted")
        with cd("concerted"):
            logger.info(f"Starting scan for concerted path.")
            scan = find_ts_GIC_scan()
            find_ts(scan, step="concerted")
    else:
        # Find TS for step 1
        os.mkdir("step_1")
        with cd("step_1"):
            logger.info(f"Starting scan for step 1.")
            scans = find_ts_scan(step="1")
            find_ts(scans, step="1")

        # Find TS for step 2
        os.mkdir("step_2")
        with cd("step_2"):
            logger.info(f"Starting scan for step 2.")
            scans = find_ts_scan(step="2")
            find_ts(scans, step="2")

    # Optimize substrate, nucleophile, product, leaving group with DFT
    jobs = []
    if config.general_options["opt_reactants"]:
        jobs.append("substrate")
        if not config.intramolecular:
            if not results.dft_atoms.get("nucleophile"):
                jobs.append("nucleophile")
    if config.general_options["opt_products"]:
        jobs.append("product")
        jobs.append("leaving_group")
    if config.agent:
        jobs.append("agent")
    
    with cd("dft_structures"):
        for name in jobs:
            os.mkdir(name)
            with cd(name):
                logger.info(f"Optimizing {name} with DFT...")
                atoms = results.xtb_atoms[name]
                opt_dft_atoms = optimize_dft(atoms)
                logger.info("...optimization completed.")
                ase.io.write(f"../../optimized_structures/{name}.xyz", opt_dft_atoms, plain=True)
                results.dft_atoms[name] = opt_dft_atoms

    # Do clustering
    do_clustering_xtb()

    # Calculate the descriptors
    if config.descriptor_options["calculate_descriptors"]:
        os.mkdir("descriptors")
        with cd("descriptors"):
            logger.info("Calculating descriptors...")
            calculate_descriptors()
            logger.info("...calculation completed.")

    # Calculate run time
    end_time = datetime.now()

    time_delta = end_time - start_time
    run_time_seconds = time_delta.total_seconds()
    run_time_str = str(time_delta)

    results.run_time = run_time_seconds
    results.end_time = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

    # Write to database
    if config.directories["database"]:
        write_reaction_database()

    logger.info(f"Program terminated succesfully. Total runtime was {run_time_str}")

if __name__ == "__main__":
    try:
        main()
    except SystemExit:
        pass
    except:
        handler()
